# Generated by Django 3.0.4 on 2020-03-27 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='publishedAt',
            new_name='publishedat',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='urlToImage',
            new_name='urltoimage',
        ),
    ]
